### ISSUE TITLE
variant names

### ISSUE THREAD

**Issue by katiesaund** [Snitkin-Lab-Umich/scripts#13]
https://github.com/Snitkin-Lab-Umich/scripts/blob/32b965c6a25fd8f26de5b8044b37e06597104a42/variant_matrix_qc.R#L87

Can you include a longer description of what the different types of variants are? true vs unmapped vs filtered vs core, etc...

**Comment by zmml** [comment]
Added numbers corresponding to variant matrix code. Let me know if you'd like more detail than that!
