### ISSUE TITLE
BLOSUM matrix choice

### ISSUE THREAD

**Issue by katiesaund** [Snitkin-Lab-Umich/scripts#16]
https://github.com/Snitkin-Lab-Umich/scripts/blob/74bc50d8d1eb69c159eba36d48a10d58811972a7/variant_parser_functions.R#L7
We learned in EEB491 that the choice of BLOSUM# could have an impact on our valuation. We should 1. investigate if changing blosum matrix chances our deleterious predictions or 2. decide we're going to ignore blosum predictions anyways so just remove it 3. does blosum# choice impact depend on which genomes we're using. 

Recall that: higher blosum number means less similar sequence.

**Comment by zmml** [comment]
Assuming we're removing del from the parser, do we use the BLOSUM matrix for anything any more? @katiesaund 

If we are removing del from the parser, we should probably make an issue about that.

**Comment by katiesaund** [comment]
I think we should get rid of del/blosum all together. Opened issue about it here: https://github.com/Snitkin-Lab-Umich/scripts/issues/17
